-- MySQL Script generated by MySQL Workbench
-- 06/18/19 12:52:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema innexu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema innexu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `innexu` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `innexu` ;

-- -----------------------------------------------------
-- Table `innexu`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`usuario` ;

CREATE TABLE IF NOT EXISTS `innexu`.`usuario` (
  `num_doc` BIGINT(10) NOT NULL COMMENT '',
  `tipo_doc` VARCHAR(25) NOT NULL COMMENT '',
  `nombre` VARCHAR(25) NOT NULL COMMENT '',
  `apellido` VARCHAR(25) NOT NULL COMMENT '',
  `telefono` BIGINT(10) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `residencia` VARCHAR(45) NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `contraseña` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`num_doc`)  COMMENT '',
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `innexu`.`mensaje` (
  `id_mensaje` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `categoria` VARCHAR(75) NOT NULL COMMENT '',
  `lugar` VARCHAR(45) NOT NULL COMMENT '',
  `texto` VARCHAR(255) NOT NULL COMMENT '',
  `foto` VARCHAR(255) NOT NULL COMMENT '',
  `video` VARCHAR(45) NOT NULL COMMENT '',
  `audio` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_mensaje`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`secretario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`secretario` ;

CREATE TABLE IF NOT EXISTS `innexu`.`secretario` (
  `num_doc` BIGINT(10) NOT NULL COMMENT '',
  `tipo_doc` VARCHAR(25) NOT NULL COMMENT '',
  `nombre` VARCHAR(25) NOT NULL COMMENT '',
  `apellido` VARCHAR(25) NOT NULL COMMENT '',
  `dependencia` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` BIGINT(10) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `usuario` VARCHAR(25) NOT NULL COMMENT '',
  `contraseña` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`num_doc`)  COMMENT '',
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`administrador` ;

CREATE TABLE IF NOT EXISTS `innexu`.`administrador` (
  `num_doc` BIGINT(10) NOT NULL COMMENT '',
  `tipo_doc` VARCHAR(25) NOT NULL COMMENT '',
  `nombres` VARCHAR(25) NOT NULL COMMENT '',
  `apellidos` VARCHAR(25) NOT NULL COMMENT '',
  `telefono` BIGINT(10) NOT NULL COMMENT '',
  `usuario` VARCHAR(25) NOT NULL COMMENT '',
  `contraseña` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`num_doc`)  COMMENT '',
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`respuesta_mens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`respuesta_mens` ;

CREATE TABLE IF NOT EXISTS `innexu`.`respuesta_mens` (
  `idrespuesta_mens` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `mensaje` VARCHAR(255) NOT NULL COMMENT '',
  `foto` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idrespuesta_mens`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`mensaje_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`mensaje_cat` ;

CREATE TABLE IF NOT EXISTS `innexu`.`mensaje_cat` (
  `idmensaje_cat` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `mensaje_id_mensaje` BIGINT(10) NOT NULL COMMENT '',
  `secretario_num_doc` BIGINT(10) NOT NULL COMMENT '',
  `respuesta_mens_idrespuesta_mens` BIGINT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idmensaje_cat`)  COMMENT '',
  INDEX `fk_mensaje_cat_mensaje1_idx` (`mensaje_id_mensaje` ASC)  COMMENT '',
  INDEX `fk_mensaje_cat_secretario1_idx` (`secretario_num_doc` ASC)  COMMENT '',
  INDEX `fk_mensaje_cat_respuesta_mens1_idx` (`respuesta_mens_idrespuesta_mens` ASC)  COMMENT '',
  CONSTRAINT `fk_mensaje_cat_mensaje1`
    FOREIGN KEY (`mensaje_id_mensaje`)
    REFERENCES `innexu`.`mensaje` (`id_mensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_cat_secretario1`
    FOREIGN KEY (`secretario_num_doc`)
    REFERENCES `innexu`.`secretario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_cat_respuesta_mens1`
    FOREIGN KEY (`respuesta_mens_idrespuesta_mens`)
    REFERENCES `innexu`.`respuesta_mens` (`idrespuesta_mens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innexu`.`usuario_mens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innexu`.`usuario_mens` ;

CREATE TABLE IF NOT EXISTS `innexu`.`usuario_mens` (
  `idusuario_mens` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario_num_doc` BIGINT(10) NOT NULL COMMENT '',
  `mensaje_id_mensaje` BIGINT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idusuario_mens`)  COMMENT '',
  INDEX `fk_usuario_mens_usuario1_idx` (`usuario_num_doc` ASC)  COMMENT '',
  INDEX `fk_usuario_mens_mensaje1_idx` (`mensaje_id_mensaje` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_mens_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `innexu`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_mens_mensaje1`
    FOREIGN KEY (`mensaje_id_mensaje`)
    REFERENCES `innexu`.`mensaje` (`id_mensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
